ivanschuetz/SwiftCharts

Examples/Examples.xcodeproj/project.pbxproj
SwiftCharts/Layers/ChartPointsCandleStickViewsLayer.swift
SwiftCharts/Layers/ChartPointsSingleViewLayer.swift
SwiftCharts/Layers/ChartPointsViewsLayer.swift

Specifically, Swift 2.0 now supports nested recursive functions.

Support for changes to Swift 2.0 in Xcode 7 beta 4.

---

Examples/Examples/Examples/CandleStickInteractiveExample.swift
Examples/Examples/Examples/GroupedAndStackedBarsExample.swift
Examples/Examples/Examples/MultipleLabelsExample.swift
SwiftCharts/Axis/ChartAxisLayer.swift
SwiftCharts/Axis/ChartAxisLayerDefault.swift
SwiftCharts/Axis/ChartAxisValuesGenerator.swift
SwiftCharts/Axis/ChartAxisXLayerDefault.swift
SwiftCharts/Axis/ChartAxisYLayerDefault.swift
SwiftCharts/AxisValues/ChartAxisValue.swift
SwiftCharts/AxisValues/ChartAxisValueDate.swift
SwiftCharts/AxisValues/ChartAxisValueFloat.swift
SwiftCharts/AxisValues/ChartAxisValueFloatScreenLoc.swift
SwiftCharts/AxisValues/ChartAxisValueInt.swift
SwiftCharts/AxisValues/ChartAxisValueString.swift
SwiftCharts/Layers/ChartCandleStickLayer.swift
SwiftCharts/Layers/ChartPointsLayer.swift
SwiftCharts/Layers/ChartPointsLineTrackerLayer.swift
SwiftCharts/Layers/ChartStackedBarsLayer.swift

referencing https://github.com/i-schuetz/SwiftCharts/pull/14
@i-schuetz based on your last comment it looks like you wanted this re-opened? I can remove if not.

(Re-opened) Prefer Double over CGFloat for scalar values

---

Examples/Examples.xcodeproj/project.pbxproj
Examples/Examples.xcodeproj/xcshareddata/xcschemes/SwiftCharts.xcscheme
Examples/SwiftCharts/Info.plist
Examples/SwiftCharts/SwiftCharts.h
Examples/SwiftChartsTests/Info.plist
Examples/SwiftChartsTests/SwiftChartsTests.swift

Hello Ivan,
I added carthage support for anyone who doesn't want to use cocoapods.
Just add "github "beneiltis/SwiftCharts"" into your Cartfile and run "carthage update".
Please make sure to add a new version tag (like 0.2.4). Otherwise carthage would ignore my additional commits.
Have a nice day.
Cheers,
Benedikt

Carthage Support

---

Examples/Examples.xcodeproj/project.pbxproj
SwiftCharts/Layers/ChartPointsLineLayer.swift
SwiftCharts/Views/StraightLinePathGenerator.swift
SwiftCharts/Views/StraigthLinePathGenerator.swift

If the points array was empty a runtime error was generated in the for loop, as the range 0..<-1 is not valid.
Also fixed spelling while I was at it.

Straightlinepath no points

---

SwiftCharts/AxisValues/ChartAxisValueDate.swift

Allows for using date values in a ChartPointTextCircleView

Return date as string for text in ChartAxisValueDate

---

SwiftCharts/Axis/ChartAxisXLayerDefault.swift
SwiftCharts/Axis/ChartAxisYHighLayerDefault.swift
SwiftCharts/Axis/ChartAxisYLowLayerDefault.swift
SwiftCharts/Drawers/ChartLineDrawer.swift

Use the axis setting's stroke width to set the axis stroke width

Dynamic axis stroke width

---

SwiftCharts/Axis/ChartAxisLabel.swift
SwiftCharts/Axis/ChartAxisLayer.swift
SwiftCharts/Axis/ChartAxisLayerDefault.swift
SwiftCharts/Axis/ChartAxisModel.swift
SwiftCharts/Axis/ChartAxisValuesGenerator.swift
SwiftCharts/Axis/ChartAxisXHighLayerDefault.swift
SwiftCharts/Axis/ChartAxisXLayerDefault.swift
SwiftCharts/Axis/ChartAxisXLowLayerDefault.swift
SwiftCharts/Axis/ChartAxisYHighLayerDefault.swift
SwiftCharts/Axis/ChartAxisYLayerDefault.swift
SwiftCharts/Axis/ChartAxisYLowLayerDefault.swift
SwiftCharts/AxisValues/ChartAxisValue.swift
SwiftCharts/Chart.swift
SwiftCharts/ChartCoordsSpace.swift
SwiftCharts/ChartLineModel.swift
SwiftCharts/ChartUtils.swift
SwiftCharts/ChartViewsConflictSolver.swift

I had the need to dive into the implementation of SwiftCharts recently, which provided me with a better understanding of some particulars but also found that some things required more explanation than was currently available. I spent some time going through some of the code to add documentation to hopefully help with this, and this PR is the result of that.
Where appropriate, I added some Unicode graphics (made in Monodraw) in order to more clearly demonstrate how a property or method would affect the graph visually. Some comments may not be correct or as precise as possible, since I'm coming at this as an outsider, so it will need to be read through to ensure it's okay to merge. This can also be seen as only a starting point where more documentation is added by myself or another …

WIP - First pass code documentation

---

SwiftCharts/Axis/ChartAxisYHighLayerDefault.swift
SwiftCharts/Axis/ChartAxisYLayerDefault.swift
SwiftCharts/Axis/ChartAxisYLowLayerDefault.swift
SwiftCharts/Drawers/ChartLabelDrawer.swift

Add textAlignment property to ChartLabelSettings which is used to properly align text in the y axis label

Change alignment of the label on y axis #99

---

SwiftCharts/Layers/ChartPointsViewsLayer.swift

Improve performance of the generateChartPointViews method in ChartPointsViewsLayer class.

Performance improvement for chart point views generation

---

Examples/Examples/ScrollExample.swift
SwiftCharts/ChartLineModel.swift
SwiftCharts/Layers/ChartPointsLineLayer.swift
SwiftCharts/Views/ChartLinesView.swift

Added Dashed Line Support based on individual ChartLineModel. Updated ScrollExample to make one of its lines be dashed.
Used the solution discussed in issue #136. PR #137 did it through changes in ChartPointsLineLayer which affects all the lines in the layer, not one (or more) individually.
(sorry for the duplicate PR)

Added Dashed Line Support based on individual ChartLineModel.

---

Examples/Examples/StackedBarsExample.swift
SwiftCharts/Layers/ChartGroupedBarsLayer.swift
SwiftCharts/Layers/ChartStackedBarsLayer.swift
SwiftCharts/Views/ChartPointViewBarStacked.swift

ChartPointViewBarStacked: added ability to round corners

---

Examples/DetailViewController.swift
Examples/Examples/BarsPlusMinusWithGradientExample.swift
Examples/Examples/BubbleExample.swift
Examples/Examples/MultiTrackerExample.swift
SwiftCharts/Axis/ChartAxisLabel.swift
SwiftCharts/Axis/ChartAxisLayerDefault.swift
SwiftCharts/Axis/ChartAxisModel.swift
SwiftCharts/Drawers/ChartLabelDrawer.swift
SwiftCharts/Layers/ChartPointsLayer.swift
SwiftCharts/Layers/ChartPointsTrackerLayer.swift
SwiftCharts/Layers/ChartStackedBarsLayer.swift

I was trying to find why the framework was crashing when rendering a chart with no data, and this helped me find the cause (I have another PR coming to help other people find the cause more quickly).
I've also hidden setters for lazy properties (because it doesn't make sense to set them from outside).

Added a bunch of CustomDebugStringConvertible implementations

---

SwiftCharts/Drawers/ChartLabelDrawer.swift

Changed ChartLabelSettings to a struct

---

SwiftCharts/Layers/ChartPointsLineLayer.swift

Use path generator for drawing line chart on context

---

Examples/Examples/MultiTrackerExample.swift
SwiftCharts.podspec
SwiftCharts/Layers/ChartPointsTouchHighlightLayer.swift

This sample app has fallen behind in maintenance.  Here are some cleanups.

Update multi-chart tracking demo.

---

SwiftCharts/Convenience/BarsChart.swift

I found that in bar chart the axis values and labels were not formatted with the provided label settings. I have modified it in this change.

Bar chart axis labels are now using provided label font and color

---

Examples/DetailViewController.swift
Examples/Examples/CubicLinesWithGradientExample.swift
Examples/Examples/RangedAxisExample.swift
Examples/MasterViewController.swift
SwiftCharts.xcodeproj/project.pbxproj
SwiftCharts/ChartLineModel.swift
SwiftCharts/Layers/ChartPointsLineLayer.swift
SwiftCharts/Views/ChartLinesView.swift

* Implemented gradients for line charts
* Added a new example to showcase the new behavior

#302 Added support for gradient line charts

---

SwiftCharts/Views/ChartPointViewBarStacked.swift

To properly use bar views we need to open also array stackViews. Before it was no chance to change the views. I checked it 👍 
//edit @i-schuetz just for notify

Required changes to open bar views

---

SwiftCharts/Views/ChartAreasView.swift

Fill area width fix: now it is equal to graph line width

---

Package.swift

Support Swift Package Manager in Xcode 11 https://github.com/i-schuetz/SwiftCharts/issues/399

Support Swift Package Manager in Xcode 11

---

SwiftCharts/Chart.swift

When building my App, I get some warnings because some variables where never used and should be created as let instead of var.

Fix Build Warnings
