ivanschuetz/SwiftCharts

SwiftCharts/Axis/ChartAxisLabel.swift, SwiftCharts/Axis/ChartAxisLayerDefault.swift, SwiftCharts/Axis/ChartAxisYLayerDefault.swift, SwiftCharts/Axis/ChartAxisYLowLayerDefault.swift, SwiftCharts/Drawers/ChartLabelDrawer.swift
This change came from a use case where we had Y axis title labels on the left and right that corresponded with two different data sets shown at the same time. We wanted both labels' baselines to be on the inside (facing the chart) and so we needed the right-side title label to be rotated 90 degrees instead of the standard -90.
This change creates a label settings subclass for the Y axis that has the same default values as before (particularly the -90 degree rotation) but allows changing the rotation value. When the value is rotated, the Y layer now uses the correct dimension of the axis title label in order to calculate the width. The label also correctly calculates its rotated bounds (previously it treated degrees as radians).
=> Allow rotating Y axis labels and fix bug when that is the case

Examples/Examples/Examples/CandleStickInteractiveExample.swift, Examples/Examples/Examples/GroupedAndStackedBarsExample.swift, Examples/Examples/Examples/MultipleLabelsExample.swift, SwiftCharts/Axis/ChartAxisLayer.swift, SwiftCharts/Axis/ChartAxisLayerDefault.swift, SwiftCharts/Axis/ChartAxisValuesGenerator.swift, SwiftCharts/Axis/ChartAxisXLayerDefault.swift, SwiftCharts/Axis/ChartAxisYLayerDefault.swift, SwiftCharts/AxisValues/ChartAxisValue.swift, SwiftCharts/AxisValues/ChartAxisValueDate.swift, SwiftCharts/AxisValues/ChartAxisValueFloat.swift, SwiftCharts/AxisValues/ChartAxisValueFloatScreenLoc.swift, SwiftCharts/AxisValues/ChartAxisValueInt.swift, SwiftCharts/AxisValues/ChartAxisValueString.swift, SwiftCharts/Layers/ChartCandleStickLayer.swift, SwiftCharts/Layers/ChartPointsLayer.swift, SwiftCharts/Layers/ChartPointsLineTrackerLayer.swift, SwiftCharts/Layers/ChartStackedBarsLayer.swift
I don't expect this pull request to get merged in it's current state, as I'm not sure if more/less conversions need to be made (e.g. ChartAxisValueFloat and ChartPoint). But I wanted to open this pull request to start a discussion about moving from CGFloat to Double where possible.
The impetus for this refactoring is that I was creating a line chart with dates at 1 minute intervals on the x-axis. Due to rounding errors when storing time intervals since 1970 in CGFloat, every 2-3 values were getting the same scalar value at draw time. Changing to Double solved this due to the extra precision.
Also, @i-schuetz: Awesome library! Thanks for all your hard work, and I hope I can contribute to this sweet project.
=> Prefer Double over CGFloat for scalar values

SwiftCharts.xcodeproj/project.pbxproj, SwiftCharts.xcodeproj/xcshareddata/xcschemes/SwiftCharts tvOS.xcscheme
This will add a tvOS target which makes swiftCharts build for tvOS.
This is working with Carthage via:
```
carthage update --platform tvos
```
=> Added tvOS target

SwiftCharts/Axis/ChartAxisLayerDefault.swift, SwiftCharts/Axis/ChartAxisXLayerDefault.swift
This removes the labelMaybeSize method. It wasn't needed in two places where it was being used, and in the other its functionality was replaced by flatMapping the array of optionals to remove the optionals before doing the reduce.
I also removed an extraneous `rows` parameter label since it was already included in the method name.
=> Remove labelMaybeSize function

SwiftCharts/Layers/ChartLayerBase.swift
Is `ChartLayerBase` available for subclassing? Currently, attempts to create a subclass from outside the module fail - Swift requires us to call `super.init()` in any subclass, but no designated initializer is visible.
We should either add a public initializer or mark it `final` to make it clear.
Thanks for your work on this project!
=> Add public init so ChartLayerBase can be subclassed

Examples/Examples/BarsExample.swift, Examples/Examples/BarsPlusMinusAndLinesExample.swift, Examples/Examples/BarsPlusMinusWithGradientExample.swift, Examples/Examples/BubbleExample.swift, Examples/Examples/CandleStickExample.swift, Examples/Examples/CandleStickInteractiveExample.swift, Examples/Examples/GroupedAndStackedBarsExample.swift, Examples/Examples/GroupedBarsExample.swift, Examples/Examples/ScrollExample.swift, Examples/Examples/StackedBarsExample.swift, SwiftCharts/AxisValues/ChartAxisValueDoubleScreenLoc.swift, SwiftCharts/AxisValues/ChartAxisValueFloat.swift, SwiftCharts/Convenience/BarsChart.swift
This PR fixes the availability annotation on the ChartAxisValueFloat class so that the compiler will warn about usage, and replaces any outstanding usages of it with ChartAxisValueDouble.
=> Fix ChartAxisValueFloat deprecation and replace existing usage

Examples/Examples/AreasExample.swift, Examples/Examples/CoordsExample.swift, Examples/Examples/CustomUnitsExample.swift, Examples/Examples/HelloWorld.swift, SwiftCharts/AxisValues/ChartAxisValue.swift, SwiftCharts/AxisValues/ChartAxisValueDate.swift, SwiftCharts/AxisValues/ChartAxisValueDouble.swift, SwiftCharts/AxisValues/ChartAxisValueDoubleScreenLoc.swift, SwiftCharts/AxisValues/ChartAxisValueFloat.swift, SwiftCharts/AxisValues/ChartAxisValueFloatScreenLoc.swift, SwiftCharts/AxisValues/ChartAxisValueInt.swift, SwiftCharts/AxisValues/ChartAxisValueString.swift, SwiftCharts/ChartPoint/ChartPoint.swift, SwiftCharts/Layers/ChartPointsLayer.swift, SwiftCharts/Layers/ChartPointsLineTrackerLayer.swift, SwiftCharts/Utils/Trendlines/TrendlineGenerator.swift, SwiftCharts/Views/ChartPointTextCircleView.swift
This PR makes 3 kinds of changes. They probably could have been split up into separate PRs, so let me know if any of them would prevent merging this entirely.
1. Classes with a `text` property that mimicked `CustomStringConvertible`'s `description` have been changed to conform to that protocol instead.
2. Aggregated the common code from ChartAxisValue subclasses into the base class.
3. A small change to make a particular filtering method in ChartPointsLayer have a more similar signature to the standard library's `filter`.
=> Make use of CustomStringConvertible, aggregate ChartAxisValue code in base class, another minor change

SwiftCharts/AxisValues/ChartAxisValueDate.swift
Being able to use a function would be extremely convenient in our application, we don't expose NSDateFormatters to everyone.
=> Use a simple closure to map dates instead of requiring a date formatter

SwiftCharts/Layers/ChartPointsLayer.swift, SwiftCharts/Layers/ChartPointsScatterLayer.swift
Make ChartPointsScatterLayer class along with its' properties and methods public for subclassing outside swift module
=> Change access levels for ChartPointsScatterLayer

SwiftCharts/Chart.swift
Change subclassing model for ChartBaseView so that it's possible to create a base view for Chart without drawRect method implemented.
Without this change drawRect method is always called but not always it's necessary (i.e. when all layers are added as sublayers instead of drawing on the context). As Apple says: "Implement this method if your view draws custom content. If your view does not do any custom drawing, avoid overriding this method."
In my case when I have a huge graph (around 60xiPad screen wide) I don't want to draw it using drawRect method - instead I would like to add only CALayers which causes significant memory consumption savings (with empty graph drawn using drawRect method memory jumps to 500mb).
=> Change ChartBaseView subclassing model

SwiftCharts.xcodeproj/project.pbxproj
This allows using `SwiftCharts` from a framework. It avoids the following warning:
```
ld: warning: linking against a dylib which is not safe for use in application extensions: SwiftCharts.framework/SwiftCharts
```
=> Set APPLICATION_EXTENSION_API_ONLY to YES

SwiftCharts/Axis/ChartAxisModel.swift
This leads to a later crash (a point is generated with a `NaN` value which makes UIKit crash).
This can be reproduced by making one of the 2 axis in `StackedBarsExample` empty.
=> ChartAxisModel: added precondition to ensure axis is not empty

Examples/Examples/AreasExample.swift, Examples/Examples/CoordsExample.swift, Examples/Examples/CustomUnitsExample.swift, Examples/Examples/EqualSpacingExample.swift, Examples/Examples/ExamplesDefaults.swift, Examples/Examples/MultiTrackerExample.swift, Examples/Examples/MultipleLabelsExample.swift, SwiftCharts/Chart.swift
This ensures that they have value semantics. With it being a `class`, any modification is **shared** amongst all users of the instance.
That means that all changes to `ExampleDefaults.chartSettingsWithPanZoom`, for example, were being propagated to every observer. Now a local copy is made.
=> Changed ChartSettings and ChartSettingsZoomPan to struct

SwiftCharts/Axis/ChartAxisValueStaticGenerator.swift
Without this, the division by 0 results in a crash later on, so better to catch this earily and tell the user what was wrong.
=> ChartAxisValueStaticGenerator: added precondition

Examples/Examples/AreasExample.swift, Examples/Examples/MultiTrackerExample.swift, SwiftCharts/Layers/ChartPointsAreaLayer.swift, SwiftCharts/Views/ChartAreasView.swift
ChartPointsAreaLayer now takes in an array of UIColors. If you pass one color in the array, the layer will just display that color. If you pass more than one color, the layer will display a gradient. In this case, the first color passed will be first color at the top of the gradient. The last color passed will be the last color at the bottom of gradient. 
To allow for full control of the visible gradient, the gradient will start at the highest pint of the visible line and end at the bottom of the visible chart. This turned out to be a challenge because the UIBezierPath generates weird bounds values. However, I was able to understand it enough to come up with the solution. It works perfectly in the AreasExample and MultiTrackerExample. Not sure how it will hold up in other cases.
I think …
=> ChartPointsAreaLayer supports Gradient

Examples/Examples/MultiTrackerExample.swift, SwiftCharts/Layers/ChartPointsTouchHighlightLayer.swift
This was submitted previously, however there were issues when squashing. This was the previous description:
Having an optional completion handler for the TouchHighlight fade animation should come in handy. For example, if there are elements that change when a user starts panning, this will allow us to revert back to the original state. For example, you can have two fixed UILabels at the top of the view that correspond to a charts below it. They are initially set to the last X and Y values of the chart. As the user pans these values change. With this completion handler, the UILabels can switch back to the original values when user stops the pan (after the fade animation). This is just one example but I'm sure it can be useful. Let me know if you would like to change the naming convention. …
=> Optional completion handler for TouchHighlight fade animation

SwiftCharts/Axis/ChartAxisLabel.swift, SwiftCharts/Axis/ChartAxisXLayerDefault.swift, SwiftCharts/Axis/ChartAxisYLayerDefault.swift, SwiftCharts/ChartAxisValueArray.swift, SwiftCharts/Drawers/ChartLabelDrawer.swift
Hi,
Because chart axis label is immutable structure we can store size of non-rotated text and use the value  instead of dynamic calculation. It's supposed to improve performance especially in case of scrolling.
=> Replaced calculation of label text size with access to cached value

SwiftCharts/Drawers/ChartLabelDrawer.swift, SwiftCharts/Layers/ChartGuideLinesLayer.swift, SwiftCharts/Layers/ChartPointsLineLayer.swift, SwiftCharts/Layers/ChartPointsViewsLayer.swift
Hi,
From time-to-time it's needed to draw something more complex instead of text labels along the axis, and the only way to do it it now is to subclass `ChartLabelDrawer`, as I see it. But to make it possible we have to make access levels to some key functions and properties less restrictive.
Also, it's useful to open some properties of layers related to delayed init to check if it's enabled externally.
Thanks in advance.
=> Less restrictive access levels to allow subclass label drawer

SwiftCharts/Views/StraightLinePathGenerator.swift
This behavior was causing a Path of straight lines to "close" its path. For example, a Path with points `(0, 2), (0, 7), (0, 5), (0, 1), (0, 4)` was finishing in `(0, 1)` instead of `(0, 4)`. For solid lines no one could see, but for dashed lines you could see that between the last 2 points, the dashed line was duplicated.
=> No need for a straight line to close() the path.

SwiftCharts/Layers/ChartGroupedBarsLayer.swift, SwiftCharts/Layers/ChartStackedBarsLayer.swift
`ChartPointViewBarStacked` owns `stackedTapHandler`, so the handler must not reference its parent. This currently creates a cycle.
This is why it's important to reason about memory ownership instead of just blindly making `self` `weak` everywhere. There's nothing special about `self` that can lead to cycles, **anything** can lead to a cycle.
=> Fixed 2 leaks setting stackedTapHandler

SwiftCharts/Views/ChartPointViewBar.swift, SwiftCharts/Views/ChartPointViewBarStacked.swift
Example:
```swift
ChartBarViewSettings(
cornerRadius: barWidth / 2.0,
roundedCorners: [.topLeft, .topRight]
)
```
=> ChartPointViewBarStacked: allowing only rounding some corners

Examples/Examples/CandleStickExample.swift, SwiftCharts/Layers/ChartCandleStickLayer.swift
Default colours for candle sticks are hardcoded as black and white in `ChartCandleStickLayer`. 
This PR allows to configure the fill colours via (optional) constructor parameters.
=> Make candle stick fill colours configurable

SwiftCharts/Chart.swift
Non fixed version causes `CALayerInvalidGeometry` exception
=> Fix dividing by zero while calculating axis inner frame

SwiftCharts.xcodeproj/project.pbxproj, SwiftCharts/Drawers/ChartLabelDrawer.swift, SwiftCharts/Layers/ChartPointsLineLayer.swift, SwiftCharts/Layers/ChartPointsViewsLayer.swift, SwiftCharts/String.swift, SwiftCharts/Views/ChartAreasView.swift, SwiftCharts/Views/ChartLinesView.swift, SwiftCharts/Views/ChartPointEllipseView.swift, SwiftCharts/Views/ChartPointViewBarGreyOut.swift, SwiftCharts/Views/ChartViewAnimators.swift
* So that SwiftCharts can compile under Swift 4.2 (See #370 )
* Run the Swift syntax conversion on master
* No tests are available to make sure nothing broke
=> Ran Swift syntax updater to bring syntax up to Swift 4.2

SwiftCharts/Drawers/ChartLabelDrawer.swift
This resolves the warning: "initialization of immutable value 'labelSize' was never used; consider replacing with assignment to '_' or removing it"
=> rm unused value 'labelSize'

Package.swift, SwiftCharts/Axis/ChartAxisLabelsConflictSolverMoveUpDown.swift, SwiftCharts/Axis/ChartAxisLabelsGenerator.swift, SwiftCharts/Axis/ChartAxisLabelsGeneratorBase.swift, SwiftCharts/Axis/ChartAxisLabelsGeneratorBasic.swift, SwiftCharts/Axis/ChartAxisLabelsGeneratorFixed.swift, SwiftCharts/Axis/ChartAxisLabelsGeneratorFunc.swift, SwiftCharts/Axis/ChartAxisLabelsGeneratorNumber.swift, SwiftCharts/Axis/ChartAxisLabelsGeneratorNumberSuffix.swift, SwiftCharts/Axis/ChartAxisValuesGeneratorXDividers.swift, SwiftCharts/Chart.swift, SwiftCharts/Drawers/ChartLabelDrawer.swift, SwiftCharts/Utils/Operators.swift
This PR fixes an issue with using SwiftCharts from another package. 
I am developing another package with SwiftCharts as a dependency, like this:
```
dependencies: [
.package(url: "https://github.com/i-schuetz/SwiftCharts.git", .branch("master"))
],
```
When building this package, Xcode does not appear to include the "SwiftCharts/Supporting Files/SwiftCharts.h" file, and so all the references to CGFloat, UIFont, etc are unresolved. Making the import of UIKit or CoreGraphics explicit solves this issue.
=> Add explicit UIKit and CoreGraphics imports
